### ISSUE TITLE
サイト内検索キーワードの、オラクルとの連動について

### ISSUE THREAD

**Issue by narueyoshida** [SibaTokyo/demo#3]
田端さま

お世話になっております。
日本航空　吉田です。

現在、オラクル側のFAQで、検索ボックスにお客様のお名前やJMB番号を入力すると、
お客さまがメールで問い合わせた内容を検索結果として表示するという不具合が発生しております。

1点確認なのですが、サイト内検索でたとえば「吉田成枝」と検索すると、
FAQ「http://faq.jal.co.jp/」ページにあるキーワードの入力ボックスに「吉田成枝」と入れたのと同じようなデータの取得方法をしますか？

管理画面側でデータを取得している場合は問題ないのですが、
検索ボックスにキーワードを入力する場合は、オラクル側で履歴を学習してしまうようなので念のため仕様を確認させていただけますか。

お手数ですがご確認よろしくお願いいたします。

日本航空　吉田

**Comment by mm-tabata** [comment]
吉田様

お世話になっております。
ナレッジワークスの田端です。
サイト内検索からFAQ検索結果ページのリンクに関する質問かと思うのですが、
認識はあっていますか。

![2015-05-25 14 44 22](https://cloud.githubusercontent.com/assets/7982808/7792390/a1858a1e-02ec-11e5-81b6-acc207410dab.png)

吉田様のご認識のとおり、入力ボックスで検索したときと同じ動きで
http://faq.jal.co.jp/app/answers/list/c/<<カテゴリーコード>>/kw/<<キーワード>>
へリンクさせています。

サイト内検索でもメールの問い合わせ内容が表示されていますでしょうか。

**Comment by narueyoshida** [comment]
田端さま

説明が悪くてすみません。
検索キーワードを入れたときに、オラクルと連動して右側のカラムにランキングで数件表示するときのロジックについてです。

オラクルのランキングの上位をとってくるときのロジックも、
http://faq.jal.co.jp/app/answers/list/c/<<カテゴリーコード>>/kw/<<キーワード>>で取得していますか？

吉田

右側に

**Comment by mm-tabata** [comment]
吉田様

回答内容がずれており、すいません。
頂いた質問の件ですが、
http://faq.jal.co.jp/app/answers/list/c/<<カテゴリーコード>>/kw/<<キーワード>>
で取得していません。


サイトマップのページ
http://faq.jal.co.jp/ci/sitemap/
から、回答ページ（例「http://faq.jal.co.jp/app/answers/detail/a_id/4467」）をクローリングして、質問と回答内容をIndexして弊社サービスの検索エンジンからの結果を表示しています。

**Comment by narueyoshida** [comment]
田端さま

私の説明が悪くてこちらこそすみません。
さっそくご回答ありがとうございました。
ケースクローズでお願いいたします。

日本航空　吉田
